plugins:
  configuration_manager_status:
    description: ''
    actions: ''
    impatcts: ''
    fail: 'Its fail message49'
    success: 'Success message!!'
    help: ''
  cron_settings:
    description: "<p>Provide tool to control codebase state.</p>\r\n"
    actions: "<p>Install and configure some advanced cron module.</p>\r\n"
    impatcts: 'If system cron doesn’t work or/and Drupal cron was setted up incorrectly it can lead to a lot of problems: <br><ul><li>Drupal will not provide system-wide defaults to running jobs at particular times, storing (caching) web pages to improve efficiency, and performing other essential tasks.</li> <li>Drupal will not periodically clean up log files</li> <li>application will not have a possibility automatically update feeds</li> <li>update manager will not have a possibility to check automatically pending updates</li> <li>search indexes that also uses cron will not index new/updated content and many other points</li></ul>'
    fail: "<p>Its fail message49</p>\r\n"
    success: "<p>Success message!!</p>\r\n"
    help: 'Check cron settings.'
    impacts: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Satis est ad hoc responsum. Quid vero? Primum quid tu dicis breve?</p>\r\n\r\n<p>&nbsp;</p>\r\n"
