stages:
  - test
  - backmerge

sonar:
  stage: test
  tags:
    - sonarqube
  script:
    - sonar-scanner -Dsonar.host.url=http://sonar.adyax-dev.com -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID
  only:
    - branches

backmerge-master:
  stage: backmerge
  image: php:7.1
  tags:
    - docker
  before_script:
    - apt-get -qq update
    - apt-get -qq -y install jq
  script:
    # Create backmerge to develop.
    - sh scripts/tools/back-merge.sh develop
  only:
    - master
