<?php

/**
 * @file
 * Main module file.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function adv_audit_theme() {
  return [
    'adv_audit' => [
      'render element' => 'elements',
    ],
    'adv_audit_run_process' => [
      'variables' => ['categories' => NULL],
      'template' => 'adv-audit-process-item',
    ],
    'adv_audit_report' => [
      'variables' => ['report' => NULL],
      'template' => 'adv-audit-report',
    ],
    'adv_audit_report_object' => [
      'variables' => [
        'title' => NULL,
        'score_point' => NULL,
        'categories' => NULL,
        'global_info' => NULL,
      ],
      'template' => 'adv-audit-report-object',
    ],
    'adv_audit_help' => [
      'variables' => ['data' => [], 'categories' => []],
      'template' => 'adv-audit-help',
    ],
  ];
}

/**
 * Prepares variables for templates.
 *
 * Default template: adv_audit.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function adv_audit_preprocess_adv_audit(array &$variables) {
  // Helpful $content variable for templates.
  $variables += ['content' => []];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for templates.
 */
function adv_audit_preprocess_adv_audit_report(&$variables) {
  /** @var \Drupal\adv_audit\Renderer\AuditReportRenderer $render */
  $render = \Drupal::service('adv_audit.renderer');
  // Wrap to renderer object.
  $variables['report'] = $render->setAuditResult($variables['report']);
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * @var \Drupal\Core\Entity\EntityInterface
 */
function adv_audit_adv_audit_presave(EntityInterface $entity) {
  // Get response object.
  $advResultResponse = $entity->get('audit_results')->getValue()[0]['value'];

  // Get global info.
  $advGlobalData = \Drupal::service('adv_audit.global_info');
  $resultsGlobal = $advGlobalData->index();

  // Set global info.
  $advResultResponse->setOverviewInfo($resultsGlobal);
  $entity->set('audit_results', serialize($advResultResponse));
}

/**
 * Implements hook_help().
 */
function adv_audit_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    case 'help.page.adv_audit':
      $renderer = \Drupal::service('renderer');
      $render_array = ['#theme' => 'adv_audit_help'];
      $manager_list = \Drupal::service('plugin.manager.adv_audit_checklist');
      $render_array['#data'] = $manager_list->getHelpPlugins();
      $output = $renderer->render($render_array);
      return $output;

    default:
      return $output;
  }
}
