<?php

/**
 * @file
 * Main module file.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function adv_audit_theme() {
  return [
    'adv_audit' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for templates.
 *
 * Default template: adv_audit.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function adv_audit_preprocess_adv_audit(array &$variables) {
  // Helpful $content variable for templates.
  $variables += ['content' => []];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  $variables['adv_audit'] = $variables['elements']['#adv_audit'];
}
